// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "not much usefull",
        "contact": {
            "name": "Asliddin",
            "url": "https://t.me/asliddindeh",
            "email": "asliddinvstalim@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirm": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register for authentication",
                "parameters": [
                    {
                        "description": "login",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CofirmEmail"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.VerifiedResponse"
                        }
                    }
                }
            }
        },
        "/customer": {
            "post": {
                "description": "this func create customer with",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "create customer with info",
                "parameters": [
                    {
                        "description": "Customer",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customer.CustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/customer.CustomerResponse"
                        }
                    }
                }
            }
        },
        "/customer/delete/{id}": {
            "delete": {
                "description": "this func delete customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "delete customer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            }
        },
        "/customer/list": {
            "get": {
                "description": "this func get all customers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "get all customers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer.ListCustomers"
                        }
                    }
                }
            }
        },
        "/customer/post/{id}": {
            "get": {
                "description": "this func get customer with post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "get customer with post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer.CustomerResponsePost"
                        }
                    }
                }
            }
        },
        "/customer/update": {
            "patch": {
                "description": "this func update customers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "update customers",
                "parameters": [
                    {
                        "description": "Customer",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customer.CustomerUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer.CustomerResponse"
                        }
                    }
                }
            }
        },
        "/customer/{id}": {
            "get": {
                "description": "this func get customer info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "get customer info",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer.CustomerResponse"
                        }
                    }
                }
            }
        },
        "/post": {
            "post": {
                "description": "this func create post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "create post with info",
                "parameters": [
                    {
                        "description": "Post",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/post.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/post.PostResponse"
                        }
                    }
                }
            }
        },
        "/post/delete/{id}": {
            "delete": {
                "description": "this func delete post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "delete post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            }
        },
        "/post/list": {
            "get": {
                "description": "this func get posts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "get posts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/post.ListAllPostResponse"
                        }
                    }
                }
            }
        },
        "/post/update": {
            "patch": {
                "description": "this func update post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "update post",
                "parameters": [
                    {
                        "description": "Post",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/post.PostUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/post.PostResponse"
                        }
                    }
                }
            }
        },
        "/post/{id}": {
            "get": {
                "description": "this func get post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "get post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/post.PostResponseCustomer"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register for authentication",
                "parameters": [
                    {
                        "description": "user data",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Register"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "success"
                    }
                }
            }
        },
        "/review": {
            "post": {
                "description": "this func create review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "create review",
                "parameters": [
                    {
                        "description": "Review",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/review.ReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/review.Review"
                        }
                    }
                }
            }
        },
        "/review/delete/{id}": {
            "delete": {
                "description": "this func delete review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "delete review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            }
        },
        "/review/{id}": {
            "get": {
                "description": "this func get review by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "get review by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/review.Review"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "customer.Address": {
            "type": "object",
            "properties": {
                "District": {
                    "type": "string"
                },
                "Street": {
                    "type": "string"
                }
            }
        },
        "customer.AddressResponse": {
            "type": "object",
            "properties": {
                "District": {
                    "type": "string"
                },
                "Street": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "customer.CustomerFullInfo": {
            "type": "object",
            "properties": {
                "Adderesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.AddressResponse"
                    }
                },
                "Bio": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "DeletedAt": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "LastName": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "string"
                },
                "Posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.PostResponse"
                    }
                },
                "Reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.ReviewList"
                    }
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "customer.CustomerRequest": {
            "type": "object",
            "properties": {
                "AccessToken": {
                    "type": "string"
                },
                "Adderesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.Address"
                    }
                },
                "Bio": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "LastName": {
                    "type": "string"
                },
                "PassWord": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "string"
                },
                "RefreshToken": {
                    "type": "string"
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "customer.CustomerResponse": {
            "type": "object",
            "properties": {
                "Adderesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.AddressResponse"
                    }
                },
                "Bio": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "LastName": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "customer.CustomerResponsePost": {
            "type": "object",
            "properties": {
                "Adderesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.AddressResponse"
                    }
                },
                "Bio": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "LastName": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "string"
                },
                "Post": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.PostResponse"
                    }
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "customer.CustomerUpdate": {
            "type": "object",
            "properties": {
                "Adderesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.AddressResponse"
                    }
                },
                "Bio": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "LastName": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "string"
                }
            }
        },
        "customer.ListCustomers": {
            "type": "object",
            "properties": {
                "ActiveCustomers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.CustomerFullInfo"
                    }
                },
                "DeletedCustomers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.CustomerFullInfo"
                    }
                }
            }
        },
        "customer.MediasResponse": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "integer"
                },
                "Link": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                }
            }
        },
        "customer.PostResponse": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "Media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer.MediasResponse"
                    }
                },
                "Name": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "customer.ReviewList": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "review": {
                    "type": "number"
                }
            }
        },
        "models.Register": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.VerifiedResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "post.AddressResponse": {
            "type": "object",
            "properties": {
                "District": {
                    "type": "string"
                },
                "Street": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "post.ListAllPostResponse": {
            "type": "object",
            "properties": {
                "ActivePost": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.PostReviewResponse"
                    }
                },
                "DeletedPost": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.PostReviewResponse"
                    }
                }
            }
        },
        "post.MediasRequest": {
            "type": "object",
            "properties": {
                "Link": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                }
            }
        },
        "post.MediasResponse": {
            "type": "object",
            "properties": {
                "Link": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "post.PostRequest": {
            "type": "object",
            "properties": {
                "CustomerId": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "Media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.MediasRequest"
                    }
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "post.PostResponse": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "CustomerId": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "Media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.MediasResponse"
                    }
                },
                "Name": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "post.PostResponseCustomer": {
            "type": "object",
            "properties": {
                "Bio": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "CustomerId": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "LastName": {
                    "type": "string"
                },
                "Media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.MediasResponse"
                    }
                },
                "Name": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                },
                "adderesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.AddressResponse"
                    }
                },
                "email": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.ReviewRespList"
                    }
                }
            }
        },
        "post.PostReviewResponse": {
            "type": "object",
            "properties": {
                "Count": {
                    "type": "integer"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "CustomerId": {
                    "type": "integer"
                },
                "DeletedAt": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "Media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.MediasResponse"
                    }
                },
                "Name": {
                    "type": "string"
                },
                "Overall": {
                    "type": "number"
                },
                "UpdatedAt": {
                    "type": "string"
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.ReviewRespList"
                    }
                }
            }
        },
        "post.PostUpdate": {
            "type": "object",
            "properties": {
                "CustomerId": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "Media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.MediasResponse"
                    }
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "post.ReviewRespList": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "review": {
                    "type": "number"
                }
            }
        },
        "review.Review": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "review": {
                    "type": "number"
                }
            }
        },
        "review.ReviewRequest": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "post_id": {
                    "type": "integer"
                },
                "review": {
                    "type": "number"
                }
            }
        },
        "v1.CofirmEmail": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "userNameOrEmail": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8070",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Review api",
	Description:      "This is reivew api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
